version: '3.8'
services:
  weaviate:
    image: semitechnologies/weaviate:1.22.4
    restart: on-failure:0
    ports:
      - "8080:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 20
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: ''
      CLUSTER_HOSTNAME: 'node1'
    volumes:
      - weaviate_data:/var/lib/weaviate
    networks:
      - multimodal-rag-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/v1/.well-known/ready"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --maxmemory 512mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    networks:
      - multimodal-rag-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - weaviate
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - WEAVIATE_URL=http://weaviate:8080
      - MEMORY_CACHE_SIZE=5000
      - REDIS_TTL=86400
      # Add your API keys here or use .env file
      - GROQ_API_KEY=${GROQ_API_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-your-secret-key-for-development-only}
    networks:
      - multimodal-rag-network
    volumes:
      - ./data:/app/data
      - ./embeddings:/app/embeddings
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Uncomment this service to run load tests
  # locust:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.locust
  #   ports:
  #     - "8089:8089"
  #   volumes:
  #     - ./:/app
  #   environment:
  #     - TARGET_URL=http://api:8000
  #   depends_on:
  #     - api
  #   networks:
  #     - multimodal-rag-network
  #   command: -f loadtest.py --host=http://api:8000

networks:
  multimodal-rag-network:
    driver: bridge

volumes:
  weaviate_data:
  redis_data: 