FROM python:3.9-slim

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Install Locust and other dependencies
RUN pip install --no-cache-dir locust pandas psutil

# Expose Locust web interface port
EXPOSE 8089

# Start Locust
ENTRYPOINT ["locust"] 